[env:esp8266]
platform = espressif8266
board = esp01_1m
framework = arduino

lib_deps =
    bblanchon/ArduinoJson@^6.21.5
    esphome/ESPAsyncTCP-esphome@^2.0.0
    https://github.com/mathieucarbou/ESPAsyncWebServer.git

monitor_speed = 115200
upload_speed = 115200